### PR TITLE
Fix unwanted connection pausing

### PR DESCRIPTION
**Pull request by ubnt-michals**
This one is pretty bad and difficult to explain...

What happens is when `CopyStreamQuery` hits it's `highWaterMark` and ends simultaneously the connection Socket ends up in the paused state. It's because after `resume` in `_detach` the ongoing `onData` event will pause the stream again (because the highWaterMark was hit).

Here is record of what happens with stack traces...
```
resume Error
    at Socket.c.connection.stream.resume (/home/m1ch4ls/play/node-pg-copy-streams/test/copy-to.js:167:27)
    at Socket.Readable.on (_stream_readable.js:836:12)
    at Socket.Readable.pipe (_stream_readable.js:690:7)
    at CopyStreamQuery.submit (/home/m1ch4ls/play/node-pg-copy-streams/copy-to.js:26:21)
    at Client._pulseQueryQueue (/home/m1ch4ls/play/node-pg-copy-streams/node_modules/pg/lib/client.js:383:43)
    at Connection.<anonymous> (/home/m1ch4ls/play/node-pg-copy-streams/node_modules/pg/lib/client.js:194:10)
    at Connection.emit (events.js:203:15)
    at Socket.<anonymous> (/home/m1ch4ls/play/node-pg-copy-streams/node_modules/pg/lib/connection.js:125:12)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
resume Error
    at Socket.c.connection.stream.resume (/home/m1ch4ls/play/node-pg-copy-streams/test/copy-to.js:167:27)
    at CopyStreamQuery._detach (/home/m1ch4ls/play/node-pg-copy-streams/copy-to.js:32:20)
    at CopyStreamQuery._transform (/home/m1ch4ls/play/node-pg-copy-streams/copy-to.js:93:14)
    at CopyStreamQuery.Transform._read (_stream_transform.js:190:10)
    at CopyStreamQuery.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at CopyStreamQuery.Writable.write (_stream_writable.js:299:11)
    at Socket.ondata (_stream_readable.js:693:20)
    at Socket.emit (events.js:203:15)
pause Error
    at Socket.c.connection.stream.pause (/home/m1ch4ls/play/node-pg-copy-streams/test/copy-to.js:172:26)
    at Socket.ondata (_stream_readable.js:706:11)
    at Socket.emit (events.js:203:15)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

The connection is then in forever paused state and unable to execute any queries.

### CODE REVIEW

**Comment by jeromew** [comment]
Thanks for detecting this. I am confused because the fix seems to work for node 10+ but not for node 6 or 8 - cf https://travis-ci.org/brianc/node-pg-copy-streams

I tested with node 7.10 and got "Error: "finish piping out" was not completed within 1000 ms"

Do you have an idea where this difference may be coming from ?

**Comment by ubnt-michals** [comment]
As per docs `final` callback is not supported option in older versions of node.

https://nodejs.org/docs/latest-v6.x/api/stream.html#stream_constructor_new_stream_writable_options

I didn't realized that... probably listening on `finish` event would work instead. I'll look at it later today.

**Comment by jeromew** [comment]
you are right this was the problem. I fixed the test and will publish a new version shortly. Thanks for finding this bug it might explain random issues that were reported.

**Comment by ubnt-michals** [comment]
@jeromew Thank you for quick merge and release, I am already testing `2.2.2` and it works great. :+1:

**Pull request merged**
