### PR TITLE
wrap reattach underlying connection stream listeners and unshift with…

### PR DESCRIPTION
**Pull request by shaunc**
… pause/resume -- fix to copyTo.

The problem in https://github.com/brianc/node-pg-copy-streams/issues/24 is caused by the fact that the "unshift" of the connection stream to put back commands following the copy out wasn't generating a "data" event, so the stream wouldn't see the "commandComplete" and "readyForQuery". 

This is solved by wrapping unshift (and _detach) in pause/resume.

I am using node 0.12.4 ... to which I upgraded after seeing error already in 0.12.0. The bug is presumably a side-effect of change in stream library code. Arguably it could be a bug in "unshift" implementation. However, since event behavior isn't documented in "unshift" documentation, perhaps it's a "feature" :).

### CODE REVIEW

**Comment by drob** [comment]
Ahhhh, very cool! This bug has bitten me many times. Thank you for hunting this down.

Do the tests pass for you locally?

**Comment by chriskinsman** [comment]
I am seeing this fail occasionally.  It is as though somehow the data is never emitted again or lost.  This is with node 4.2.2

**Comment by shaunc** [comment]
(nb ... latest shaunc/master is no longer suitable for a pull request. Merges work by ebiven, from a fork he later removed. It has a lot of cleanup including this, but unfortunately he also converted to coffeescript. This repo doesn't seem to be on @brianc's list of favorites to lavish time on, but given interest by owner I could try to port some of this work back -- or fork from shaunc/node-pg-copy-streams yourself...)

**Comment by cbaron** [comment]
Let me know if there's anything I can do here.  Trying to write my own image server, and this issue isn't helping my cause.

**Comment by jeromew** [comment]
I haven't had these issues with 1.2.0 but I am not sure what needs to be tested. I realize 1.2.0 has some fixes that were already in this coffeescript version so maybe 1.2.0 fixes the problem.

I am closing this PR as a port to coffeescript is not on the roadmap and the diff is too big to single out atomic issues.

The fact that I am closing this does not mean that 1.2.0 is feature equivalent with this PR I really have no idea. It simply means that I don't see a clear way to merge this nor to reproduce the mentioned issues.

**Pull request closed without merging**
