### PR TITLE
Add a test for NoticeResponse handling

### PR DESCRIPTION
**Pull request by jeromew**
This adds a test for the Notice response. It should break travis intentionally.

I have another PR that I will send later that rewrites the algorithm to handle these cases.

### CODE REVIEW

**Comment by jeromew** [comment]
.. And it does not break. now I have to understand why ;-)

**Comment by jeromew** [comment]
I might have found the reason. I suppose that travis has

    SET SESSION client_min_messages = ERROR;

in their setup

**Comment by brianc** [comment]
cool - do you want me to wait to merge this?

**Comment by jeromew** [comment]
@brianc no you can merge it if you want, I pushed the fix on #52 if you want to check before merging.

**Comment by brianc** [comment]
@jeromew travis wont relaunch tests on #52 unless you add a commit to #52. I'll merge this!

**Pull request merged**
