### PR TITLE
Use mocha for tests

### PR DESCRIPTION
**Pull request by pspi**
Convert existing tests to use mocha. Remove old way of timeouting tests with gonna() and rely on mocha test runner's built-in timeout.

### CODE REVIEW

**Comment by pspi** [comment]
TODO:

- [ ] Replace test assertions using Node core assert module with mocha matchers.

**Comment by jeromew** [comment]
Great! thank !
it is always a leap of faith to migrate tests like that but it looks good to me. I'll do some checks by introducing some bugs once it is merged.
Can I merge it ?

**Comment by pspi** [comment]
> Can I merge it ?
 
Yes.

I've got few test cases that I'm planning to add, but I'll put them in a separate PR.

**Comment by jeromew** [comment]
ok I merged it.

following your PR's on travis/prettier I found a way to make the
conditional on v8 work so travis now checks with prettier when node <> v8
:-)

I'll try to double-check the test port to mocha by adding some bugs in the
code to see if they are correctly detected.

Jérôme

**Pull request merged**
